import { lazy, type ComponentType, type LazyExoticComponent } from "react";
import {
  AboutIcon,
  BrowserIcon,
  CalculatorIcon,
  ContactIcon,
  DinoIcon,
  DoomIcon,
  EditorIcon,
  FilesIcon,
  GamesIcon,
  HextrisIcon,
  MarkdownIcon,
  MusicIcon,
  NotesIcon,
  PaintIcon,
  PdfIcon,
  PhotosIcon,
  ProjectsIcon,
  ResumeIcon,
  SettingsIcon,
  SnakeIcon,
  TerminalIcon,
  TetrisIcon,
  V86Icon,
  VideoIcon,
} from "@/components/icons/apps";
import { getBaseName } from "@/lib/utils";
import type { AppComponentProps, AppDefinition, AppId } from "@/types/system";

const componentCache = new Map<AppId, LazyExoticComponent<ComponentType<AppComponentProps>>>();

function defineApp(definition: AppDefinition): AppDefinition {
  return {
    minSize: { width: 320, height: 240 },
    resizable: true,
    mobileMaximized: true,
    ...definition,
  };
}

const registry: Record<AppId, AppDefinition> = {
  about: defineApp({
    id: "about",
    title: "About",
    description: "Bio, strengths, skills, and recruiter summary.",
    category: "Portfolio",
    icon: AboutIcon,
    accent: "#7bd0ff",
    defaultPosition: { x: 120, y: 88 },
    defaultSize: { width: 880, height: 640 },
    load: async () => ({ default: (await import("@/components/apps/about-app")).AboutApp }),
  }),
  projects: defineApp({
    id: "projects",
    title: "Projects",
    description: "Featured work, visuals, and case study launchers.",
    category: "Portfolio",
    icon: ProjectsIcon,
    accent: "#ff9960",
    defaultPosition: { x: 152, y: 96 },
    defaultSize: { width: 980, height: 680 },
    load: async () => ({ default: (await import("@/components/apps/projects-app")).ProjectsApp }),
  }),
  contact: defineApp({
    id: "contact",
    title: "Contact",
    description: "Direct contact options and social links.",
    category: "Portfolio",
    icon: ContactIcon,
    accent: "#ffd374",
    defaultPosition: { x: 198, y: 118 },
    defaultSize: { width: 880, height: 520 },
    load: async () => ({ default: (await import("@/components/apps/contact-app")).ContactApp }),
  }),
  files: defineApp({
    id: "files",
    title: "File Explorer",
    description: "Browse the virtual filesystem and open portfolio assets.",
    category: "Workspace",
    icon: FilesIcon,
    accent: "#84b6ff",
    defaultPosition: { x: 176, y: 84 },
    defaultSize: { width: 940, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/file-explorer-app")).FileExplorerApp }),
    resolveTitle: (payload) =>
      payload?.directoryPath ? `Explorer - ${getBaseName(payload.directoryPath)}` : "File Explorer",
    jumpList: [
      { id: "open-home", label: "Home", payload: { directoryPath: "/" } },
      { id: "open-desktop", label: "Desktop", payload: { directoryPath: "/Desktop" } },
      { id: "open-documents", label: "Documents", payload: { directoryPath: "/Documents" } },
      { id: "open-media", label: "Media", payload: { directoryPath: "/Media" } },
    ],
  }),
  notes: defineApp({
    id: "notes",
    title: "Notes",
    description: "Create and edit plain text notes and markdown files.",
    category: "Workspace",
    icon: NotesIcon,
    accent: "#ffe58f",
    defaultPosition: { x: 200, y: 100 },
    defaultSize: { width: 900, height: 600 },
    multiple: false,
    load: async () => ({ default: (await import("@/components/apps/notes-app")).NotesApp }),
    resolveTitle: (payload) => (payload?.filePath ? getBaseName(payload.filePath) : "Notes"),
    jumpList: [
      { id: "new-note", label: "New Note" },
    ],
  }),
  music: defineApp({
    id: "music",
    title: "Music Player",
    description: "Mini player for local MP3 and WAV files with a folder-based playlist.",
    category: "Lab",
    icon: MusicIcon,
    accent: "#82f4d7",
    defaultPosition: { x: 218, y: 104 },
    defaultSize: { width: 860, height: 600 },
    load: async () => ({ default: (await import("@/components/apps/music-player-app")).MusicPlayerApp }),
    resolveTitle: (payload) =>
      payload?.filePath ? `Music - ${getBaseName(payload.filePath)}` : "Music Player",
  }),
  games: defineApp({
    id: "games",
    title: "Games",
    description: "Arcade hub with bundled open-source games inside the desktop shell.",
    category: "Lab",
    icon: GamesIcon,
    accent: "#8ba8ff",
    hidden: true,
    defaultPosition: { x: 212, y: 100 },
    defaultSize: { width: 900, height: 620 },
    load: async () => ({ default: (await import("@/components/apps/games-app")).GamesApp }),
  }),
  snake: defineApp({
    id: "snake",
    title: "Snake",
    description: "Compact arcade snake game built into the desktop shell.",
    category: "Lab",
    icon: SnakeIcon,
    accent: "#8bff9f",
    hidden: true,
    defaultPosition: { x: 232, y: 108 },
    defaultSize: { width: 760, height: 560 },
    load: async () => ({ default: (await import("@/components/apps/snake-app")).SnakeApp }),
  }),
  tetris: defineApp({
    id: "tetris",
    title: "Tetris",
    description: "Falling-block arcade game with a compact board-first layout.",
    category: "Lab",
    icon: TetrisIcon,
    accent: "#84b6ff",
    hidden: true,
    defaultPosition: { x: 244, y: 116 },
    defaultSize: { width: 820, height: 620 },
    load: async () => ({ default: (await import("@/components/apps/tetris-app")).TetrisApp }),
  }),
  dino: defineApp({
    id: "dino",
    title: "Dino",
    description: "Runner port currently paused while a safer local version is prepared.",
    category: "Lab",
    icon: DinoIcon,
    accent: "#ffd27d",
    hidden: true,
    defaultPosition: { x: 252, y: 132 },
    defaultSize: { width: 780, height: 560 },
    load: async () => ({ default: (await import("@/components/apps/dino-app")).DinoApp }),
  }),
  doom: defineApp({
    id: "doom",
    title: "Doom",
    description: "Experimental port currently paused during the security hardening pass.",
    category: "Lab",
    icon: DoomIcon,
    accent: "#ff8a5c",
    hidden: true,
    defaultPosition: { x: 224, y: 104 },
    defaultSize: { width: 980, height: 720 },
    load: async () => ({ default: (await import("@/components/apps/doom-app")).DoomApp }),
  }),
  hextris: defineApp({
    id: "hextris",
    title: "Hextris",
    description: "Puzzle port currently paused while a safer local replacement is prepared.",
    category: "Lab",
    icon: HextrisIcon,
    accent: "#84b6ff",
    hidden: true,
    defaultPosition: { x: 236, y: 108 },
    defaultSize: { width: 860, height: 640 },
    load: async () => ({ default: (await import("@/components/apps/hextris-app")).HextrisApp }),
  }),
  v86: defineApp({
    id: "v86",
    title: "Virtual x86",
    description: "Experimental x86 emulator with isolated, basic disk boot support.",
    category: "Lab",
    icon: V86Icon,
    accent: "#7dd5ff",
    defaultPosition: { x: 198, y: 86 },
    defaultSize: { width: 960, height: 720 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/v86-app")).VirtualX86App }),
    resolveTitle: (payload) =>
      payload?.filePath ? `Virtual x86 - ${getBaseName(payload.filePath)}` : "Virtual x86",
  }),
  terminal: defineApp({
    id: "terminal",
    title: "Terminal",
    description: "Explore the portfolio through commands and files.",
    category: "Workspace",
    icon: TerminalIcon,
    accent: "#92ffb6",
    defaultPosition: { x: 214, y: 126 },
    defaultSize: { width: 820, height: 520 },
    load: async () => ({ default: (await import("@/components/apps/terminal-app")).TerminalApp }),
    jumpList: [
      { id: "new-terminal", label: "New Terminal" },
    ],
  }),
  editor: defineApp({
    id: "editor",
    title: "Code Editor",
    description: "Monaco editor for virtual text and code files.",
    category: "Workspace",
    icon: EditorIcon,
    accent: "#7fa2ff",
    defaultPosition: { x: 186, y: 92 },
    defaultSize: { width: 900, height: 620 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/code-editor-app")).CodeEditorApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Editor - ${getBaseName(payload.filePath)}` : "Code Editor"),
  }),
  photos: defineApp({
    id: "photos",
    title: "Photos",
    description: "Image viewer for photography and project visuals.",
    category: "Media",
    icon: PhotosIcon,
    accent: "#f8a6ff",
    defaultPosition: { x: 216, y: 104 },
    defaultSize: { width: 900, height: 640 },
    multiple: false,
    load: async () => ({ default: (await import("@/components/apps/photo-viewer-app")).PhotoViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Photos - ${getBaseName(payload.filePath)}` : "Photos"),
  }),
  video: defineApp({
    id: "video",
    title: "Video Player",
    description: "Plays a selected video file or demo reel.",
    category: "Media",
    icon: VideoIcon,
    accent: "#84fff2",
    defaultPosition: { x: 238, y: 116 },
    defaultSize: { width: 920, height: 620 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/media-viewer-app")).MediaViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Video - ${getBaseName(payload.filePath)}` : "Video Player"),
  }),
  markdown: defineApp({
    id: "markdown",
    title: "Markdown Viewer",
    description: "Reader for portfolio notes, docs, and case studies.",
    category: "Workspace",
    icon: MarkdownIcon,
    accent: "#ffcf8f",
    defaultPosition: { x: 178, y: 92 },
    defaultSize: { width: 820, height: 600 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/markdown-viewer-app")).MarkdownViewerApp }),
    resolveTitle: (payload) =>
      payload?.filePath ? `Document - ${getBaseName(payload.filePath)}` : "Markdown Viewer",
  }),
  settings: defineApp({
    id: "settings",
    title: "Settings",
    description: "Theme, wallpaper, and desktop environment preferences.",
    category: "System",
    icon: SettingsIcon,
    accent: "#bfa7ff",
    defaultPosition: { x: 248, y: 122 },
    defaultSize: { width: 780, height: 560 },
    load: async () => ({ default: (await import("@/components/apps/settings-app")).SettingsApp }),
    jumpList: [
      { id: "open-settings", label: "Appearance & Wallpaper" },
    ],
  }),
  browser: defineApp({
    id: "browser",
    title: "Browser",
    description: "Embedded link workspace for external sites and bookmarks.",
    category: "Workspace",
    icon: BrowserIcon,
    accent: "#8be0ff",
    defaultPosition: { x: 188, y: 82 },
    defaultSize: { width: 940, height: 660 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/browser-app")).BrowserApp }),
    resolveTitle: (payload) => payload?.externalUrl ?? "Browser",
  }),
  pdf: defineApp({
    id: "pdf",
    title: "PDF Viewer",
    description: "Page-based PDF reading, zooming, and printing.",
    category: "Workspace",
    icon: PdfIcon,
    accent: "#ffe58f",
    defaultPosition: { x: 208, y: 84 },
    defaultSize: { width: 880, height: 660 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/pdf-viewer-app")).PdfViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? getBaseName(payload.filePath) : "PDF Viewer"),
  }),
  paint: defineApp({
    id: "paint",
    title: "Paint",
    description: "Minimal image editing workspace for portfolio assets and uploads.",
    category: "Lab",
    icon: PaintIcon,
    accent: "#ffb680",
    defaultPosition: { x: 198, y: 84 },
    defaultSize: { width: 900, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/paint-app")).PaintApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Paint - ${getBaseName(payload.filePath)}` : "Paint"),
  }),
  resume: defineApp({
    id: "resume",
    title: "Resume",
    description: "Inline resume viewer with download access.",
    category: "Portfolio",
    icon: ResumeIcon,
    accent: "#ffe58f",
    hidden: true,
    defaultPosition: { x: 208, y: 84 },
    defaultSize: { width: 860, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/pdf-viewer-app")).PdfViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? getBaseName(payload.filePath) : "Resume"),
  }),
  calculator: defineApp({
    id: "calculator",
    title: "Calculator",
    description: "Standard calculator with keyboard support.",
    category: "System",
    icon: CalculatorIcon,
    accent: "#a8ff80",
    defaultPosition: { x: 280, y: 140 },
    defaultSize: { width: 320, height: 480 },
    minSize: { width: 280, height: 420 },
    resizable: false,
    load: async () => ({ default: (await import("@/components/apps/calculator-app")).CalculatorApp }),
  }),
};

export function getAppRegistry() {
  return Object.values(registry).filter((app) => !app.hidden);
}

export function getAppDefinition(appId: AppId) {
  return registry[appId];
}

export function getAppComponent(appId: AppId) {
  const cachedComponent = componentCache.get(appId);

  if (cachedComponent) {
    return cachedComponent;
  }

  const component = lazy(registry[appId].load);
  componentCache.set(appId, component);
  return component;
}

export function canLaunchMultiple(appId: AppId) {
  return Boolean(registry[appId].multiple);
}
