import { lazy, type ComponentType, type LazyExoticComponent } from "react";
import {
  Bird,
  BookText,
  BriefcaseBusiness,
  Brush,
  Clapperboard,
  Code2,
  Cpu,
  FolderOpen,
  Gamepad2,
  Globe2,
  Hexagon,
  Image,
  Mail,
  MonitorCog,
  Music4,
  ScrollText,
  Skull,
  TerminalSquare,
  UserRound,
} from "lucide-react";
import { getBaseName } from "@/lib/utils";
import type { AppComponentProps, AppDefinition, AppId, AppModule } from "@/types/system";

const componentCache = new Map<AppId, LazyExoticComponent<ComponentType<AppComponentProps>>>();

function defineApp(definition: AppDefinition): AppDefinition {
  return {
    minSize: { width: 320, height: 240 },
    resizable: true,
    mobileMaximized: true,
    ...definition,
  };
}

const registry: Record<AppId, AppDefinition> = {
  about: defineApp({
    id: "about",
    title: "About",
    description: "Bio, strengths, skills, and recruiter summary.",
    category: "Portfolio",
    icon: UserRound,
    accent: "#7bd0ff",
    defaultPosition: { x: 120, y: 88 },
    defaultSize: { width: 880, height: 640 },
    load: async () => ({ default: (await import("@/components/apps/about-app")).AboutApp }),
  }),
  projects: defineApp({
    id: "projects",
    title: "Projects",
    description: "Featured work, visuals, and case study launchers.",
    category: "Portfolio",
    icon: BriefcaseBusiness,
    accent: "#ff9960",
    defaultPosition: { x: 152, y: 96 },
    defaultSize: { width: 980, height: 680 },
    load: async () => ({ default: (await import("@/components/apps/projects-app")).ProjectsApp }),
  }),
  contact: defineApp({
    id: "contact",
    title: "Contact",
    description: "Direct contact options and social links.",
    category: "Portfolio",
    icon: Mail,
    accent: "#ffd374",
    defaultPosition: { x: 198, y: 118 },
    defaultSize: { width: 720, height: 520 },
    load: async () => ({ default: (await import("@/components/apps/contact-app")).ContactApp }),
  }),
  files: defineApp({
    id: "files",
    title: "File Explorer",
    description: "Browse the virtual filesystem and open portfolio assets.",
    category: "Workspace",
    icon: FolderOpen,
    accent: "#84b6ff",
    defaultPosition: { x: 176, y: 84 },
    defaultSize: { width: 940, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/file-explorer-app")).FileExplorerApp }),
    resolveTitle: (payload) =>
      payload?.directoryPath ? `Explorer - ${getBaseName(payload.directoryPath)}` : "File Explorer",
  }),
  notes: defineApp({
    id: "notes",
    title: "Notes",
    description: "Create and edit plain text notes and markdown files.",
    category: "Workspace",
    icon: BookText,
    accent: "#ffe58f",
    defaultPosition: { x: 200, y: 100 },
    defaultSize: { width: 900, height: 600 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/notes-app")).NotesApp }),
    resolveTitle: (payload) => (payload?.filePath ? getBaseName(payload.filePath) : "Notes"),
  }),
  music: defineApp({
    id: "music",
    title: "Music Player",
    description: "Mini player for local MP3 and WAV files with a folder-based playlist.",
    category: "Media",
    icon: Music4,
    accent: "#82f4d7",
    defaultPosition: { x: 218, y: 104 },
    defaultSize: { width: 860, height: 600 },
    load: async () => ({ default: (await import("@/components/apps/music-player-app")).MusicPlayerApp }),
    resolveTitle: (payload) =>
      payload?.filePath ? `Music - ${getBaseName(payload.filePath)}` : "Music Player",
  }),
  games: defineApp({
    id: "games",
    title: "Games",
    description: "Arcade hub with bundled open-source games inside the desktop shell.",
    category: "Media",
    icon: Gamepad2,
    accent: "#8ba8ff",
    defaultPosition: { x: 212, y: 100 },
    defaultSize: { width: 900, height: 620 },
    load: async () => ({ default: (await import("@/components/apps/games-app")).GamesApp }),
  }),
  snake: defineApp({
    id: "snake",
    title: "Snake",
    description: "Compact arcade snake game built into the desktop shell.",
    category: "Media",
    icon: Gamepad2,
    accent: "#8bff9f",
    defaultPosition: { x: 232, y: 108 },
    defaultSize: { width: 760, height: 560 },
    load: async () => ({ default: (await import("@/components/apps/snake-app")).SnakeApp }),
  }),
  tetris: defineApp({
    id: "tetris",
    title: "Tetris",
    description: "Falling-block arcade game with a compact board-first layout.",
    category: "Media",
    icon: Gamepad2,
    accent: "#84b6ff",
    defaultPosition: { x: 244, y: 116 },
    defaultSize: { width: 820, height: 620 },
    load: async () => ({ default: (await import("@/components/apps/tetris-app")).TetrisApp }),
  }),
  dino: defineApp({
    id: "dino",
    title: "Dino",
    description: "The Chromium offline runner bundled locally for desktop-window play.",
    category: "Media",
    icon: Bird,
    accent: "#ffd27d",
    defaultPosition: { x: 252, y: 132 },
    defaultSize: { width: 780, height: 560 },
    load: async () => ({ default: (await import("@/components/apps/dino-app")).DinoApp }),
  }),
  doom: defineApp({
    id: "doom",
    title: "Doom",
    description: "Freedoom content packaged into a local js-dos bundle.",
    category: "Media",
    icon: Skull,
    accent: "#ff8a5c",
    defaultPosition: { x: 224, y: 104 },
    defaultSize: { width: 980, height: 720 },
    load: async () => ({ default: (await import("@/components/apps/doom-app")).DoomApp }),
  }),
  hextris: defineApp({
    id: "hextris",
    title: "Hextris",
    description: "Open-source puzzle game bundled into the desktop shell.",
    category: "Media",
    icon: Hexagon,
    accent: "#84b6ff",
    defaultPosition: { x: 236, y: 108 },
    defaultSize: { width: 860, height: 640 },
    load: async () => ({ default: (await import("@/components/apps/hextris-app")).HextrisApp }),
  }),
  v86: defineApp({
    id: "v86",
    title: "Virtual x86",
    description: "Experimental x86 emulator with isolated, basic disk boot support.",
    category: "System",
    icon: Cpu,
    accent: "#7dd5ff",
    defaultPosition: { x: 198, y: 86 },
    defaultSize: { width: 960, height: 720 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/v86-app")).VirtualX86App }),
    resolveTitle: (payload) =>
      payload?.filePath ? `Virtual x86 - ${getBaseName(payload.filePath)}` : "Virtual x86",
  }),
  terminal: defineApp({
    id: "terminal",
    title: "Terminal",
    description: "Explore the portfolio through commands and files.",
    category: "Workspace",
    icon: TerminalSquare,
    accent: "#92ffb6",
    defaultPosition: { x: 214, y: 126 },
    defaultSize: { width: 820, height: 520 },
    load: async () => ({ default: (await import("@/components/apps/terminal-app")).TerminalApp }),
  }),
  editor: defineApp({
    id: "editor",
    title: "Code Editor",
    description: "Monaco editor for virtual text and code files.",
    category: "Workspace",
    icon: Code2,
    accent: "#7fa2ff",
    defaultPosition: { x: 186, y: 92 },
    defaultSize: { width: 900, height: 620 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/code-editor-app")).CodeEditorApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Editor - ${getBaseName(payload.filePath)}` : "Code Editor"),
  }),
  photos: defineApp({
    id: "photos",
    title: "Photos",
    description: "Image viewer for photography and project visuals.",
    category: "Media",
    icon: Image,
    accent: "#f8a6ff",
    defaultPosition: { x: 216, y: 104 },
    defaultSize: { width: 900, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/photo-viewer-app")).PhotoViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Photos - ${getBaseName(payload.filePath)}` : "Photos"),
  }),
  video: defineApp({
    id: "video",
    title: "Video Player",
    description: "Plays a selected video file or demo reel.",
    category: "Media",
    icon: Clapperboard,
    accent: "#84fff2",
    defaultPosition: { x: 238, y: 116 },
    defaultSize: { width: 920, height: 620 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/media-viewer-app")).MediaViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Video - ${getBaseName(payload.filePath)}` : "Video Player"),
  }),
  markdown: defineApp({
    id: "markdown",
    title: "Markdown Viewer",
    description: "Reader for portfolio notes, docs, and case studies.",
    category: "Workspace",
    icon: ScrollText,
    accent: "#ffcf8f",
    defaultPosition: { x: 178, y: 92 },
    defaultSize: { width: 820, height: 600 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/markdown-viewer-app")).MarkdownViewerApp }),
    resolveTitle: (payload) =>
      payload?.filePath ? `Document - ${getBaseName(payload.filePath)}` : "Markdown Viewer",
  }),
  settings: defineApp({
    id: "settings",
    title: "Settings",
    description: "Theme, wallpaper, and desktop environment preferences.",
    category: "System",
    icon: MonitorCog,
    accent: "#bfa7ff",
    defaultPosition: { x: 248, y: 122 },
    defaultSize: { width: 780, height: 560 },
    load: async () => ({ default: (await import("@/components/apps/settings-app")).SettingsApp }),
  }),
  browser: defineApp({
    id: "browser",
    title: "Browser",
    description: "Embedded link workspace for external sites and bookmarks.",
    category: "Workspace",
    icon: Globe2,
    accent: "#8be0ff",
    defaultPosition: { x: 188, y: 82 },
    defaultSize: { width: 940, height: 660 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/browser-app")).BrowserApp }),
    resolveTitle: (payload) => payload?.externalUrl ?? "Browser",
  }),
  pdf: defineApp({
    id: "pdf",
    title: "PDF Viewer",
    description: "Page-based PDF reading, zooming, and printing.",
    category: "Workspace",
    icon: BookText,
    accent: "#ffe58f",
    defaultPosition: { x: 208, y: 84 },
    defaultSize: { width: 880, height: 660 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/pdf-viewer-app")).PdfViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? getBaseName(payload.filePath) : "PDF Viewer"),
  }),
  paint: defineApp({
    id: "paint",
    title: "Paint",
    description: "Minimal image editing workspace for portfolio assets and uploads.",
    category: "Media",
    icon: Brush,
    accent: "#ffb680",
    defaultPosition: { x: 198, y: 84 },
    defaultSize: { width: 900, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/paint-app")).PaintApp }),
    resolveTitle: (payload) => (payload?.filePath ? `Paint - ${getBaseName(payload.filePath)}` : "Paint"),
  }),
  resume: defineApp({
    id: "resume",
    title: "Resume",
    description: "Inline resume viewer with download access.",
    category: "Portfolio",
    icon: BookText,
    accent: "#ffe58f",
    hidden: true,
    defaultPosition: { x: 208, y: 84 },
    defaultSize: { width: 860, height: 640 },
    multiple: true,
    load: async () => ({ default: (await import("@/components/apps/pdf-viewer-app")).PdfViewerApp }),
    resolveTitle: (payload) => (payload?.filePath ? getBaseName(payload.filePath) : "Resume"),
  }),
};

export function getAppRegistry() {
  return Object.values(registry).filter((app) => !app.hidden);
}

export function getAppDefinition(appId: AppId) {
  return registry[appId];
}

export function getAppComponent(appId: AppId) {
  const cachedComponent = componentCache.get(appId);

  if (cachedComponent) {
    return cachedComponent;
  }

  const component = lazy(registry[appId].load);
  componentCache.set(appId, component);
  return component;
}

export function canLaunchMultiple(appId: AppId) {
  return Boolean(registry[appId].multiple);
}
